name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: Geode-solutions/actions/.github/workflows/deploy.yml@master
    with:
      name: OPENGEODE_GEOSCIENCESIO
      repos: OpenGeode;OpenGeode-IO;OpenGeode-Geosciences
    secrets: inherit
