name: Test PR

on:
  pull_request:

jobs:
  test:
    uses: Geode-solutions/actions/.github/workflows/cpp-test-pr.yml@master
    with:
      name: OPENGEODE_GEOSCIENCESIO
      repos: OpenGeode;OpenGeode-IO;OpenGeode-Geosciences
    secrets: inherit
